FROM ruby:latest


# ------------------------------------------------------------------------------------ deconf error fix
ENV DEBIAN_FRONTEND noninteractive
ENV DEBCONF_NOWARNINGS="yes"


# ------------------------------------------------------------------------------------ general
ENV SHELL=/bin/bash

RUN apt-get update && \
  apt-get install apt-utils -y

RUN apt-get update && \
  apt-get upgrade -y && \
  apt-get install git -y && \
  apt-get install bash-completion && \
  apt-get install curl -y && \
  apt-get install ripgrep && \
  apt-get install fzf && \
  apt-get install build-essential -y
WORKDIR /root


# ------------------------------------------------------------------------------------ nvim
RUN curl -LO https://github.com/neovim/neovim/releases/download/v0.7.0/nvim.appimage && \
  chmod u+x nvim.appimage && \
  ./nvim.appimage --appimage-extract && \
  mv squashfs-root / && \
  ln -s /squashfs-root/AppRun /usr/bin/nvim && \
  rm nvim.appimage


# ------------------------------------------------------------------------------------ add packer
RUN git clone --depth 1 https://github.com/wbthomason/packer.nvim ~/.local/share/nvim/site/pack/packer/start/packer.nvim


# ------------------------------------------------------------------------------------ personal nvim config
RUN git clone https://github.com/ldoo22/ovim.git ~/.config/nvim


# ------------------------------------------------------------------------------------ install packer plugins
RUN nvim --headless -c 'autocmd User PackerComplete quitall' -c 'silent PackerSync'; exit 0 # Not very correct
RUN nvim --headless -c 'autocmd User PackerComplete quitall' -c 'silent PackerSync'; exit 0


# ------------------------------------------------------------------------------------ install rails
RUN gem install rails


CMD ["sleep", "infinity"]
